language: cpp
# Select Ubuntu version
dist: bionic

# Install dependency
before_install:
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo add-apt-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
    - sudo add-apt-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
    - sudo add-apt-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get -y install flex bison clang-6.0 clang-7 clang-8 clang-9 clang-10 cmake cmake-data g++-6 g++-7 g++-8 g++-9

env:
    - CC=/usr/bin/clang-6.0 CXX=/usr/bin/clang++-6.0
    - CC=/usr/bin/clang-7 CXX=/usr/bin/clang++-7
    - CC=/usr/bin/clang-8 CXX=/usr/bin/clang++-8
    - CC=/usr/bin/clang-9 CXX=/usr/bin/clang++-9
    - CC=/usr/bin/clang-10 CXX=/usr/bin/clang++-10
    - CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6
    - CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7
    - CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8
    - CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9

before_script:
    - mkdir -p build && cd build

# Build main and tests
script:
    - bison -v ../src/ompparser.yy && ! cat ompparser.output | grep conflict
    - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
    - make

