!$OMP PARALLEL
!$OMP     DO PRIVATE(I)
!$OMP     SINGLE
!$OMP     END SINGLE
!$OMP     DO PRIVATE(I,Y,ERROR), REDUCTION(+:TOOBIG)
!$OMP     MASKED
!$OMP     END MASKED
!$OMP   BARRIER
!$OMP   MASKED FILTER(1)
!$OMP   END MASKED
!$OMP END PARALLEL
