!$OMP PARALLEL SHARED(X, Y) PRIVATE(IX_NEXT, IY_NEXT)
!$OMP CRITICAL(XAXIS) HINT(OMP_SYNC_HINT_CONTENDED)
!$OMP END CRITICAL(XAXIS)
!$OMP CRITICAL(YAXIS) HINT(OMP_SYNC_HINT_CONTENDED)
!$OMP END CRITICAL(YAXIS)
!$OMP END PARALLEL
