#pragma omp target enter data map(alloc: h_matrix[dev][0 : 1000])
#pragma omp target map(alloc: h_matrix[dev][0 : 1000])
#pragma omp target exit data map(from: h_matrix[dev][0 : 1000])
#pragma omp target enter data map(alloc: h_matrix[dev][0 : 1000]) device(dev)
#pragma omp target map(alloc: h_matrix[dev][0 : 1000]) device(dev)
#pragma omp target exit data map(from: h_matrix[dev][0 : 1000]) device(dev)
#pragma omp target map (from: _ompvv_isOffloadingOn)
