name: GNU CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        gnu: [9, 10, 11, 12, 13, 14]

    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/gcc-${{ matrix.gnu }}
      CXX: /usr/bin/g++-${{ matrix.gnu }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bison \
          build-essential \
          cmake \
          flex \
          g++-${{ matrix.gnu }}

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/
        mkdir build
        cd build
        bison -v ../src/ompparser.yy && ! cat ompparser.output | grep conflict
        cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON ..
        make tester

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        ! ../test_folder.sh ../tests | grep FAILED | grep [1-9]
