name: LLVM CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        llvm: [17, 18, 19, 20]

    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/clang-${{ matrix.llvm }}
      CXX: /usr/bin/clang++-${{ matrix.llvm }}

    steps:
    - uses: actions/checkout@v4

    - name: Add LLVM repository key
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

    - name: Add LLVM repository on Ubuntu 24.04
      if: ${{ matrix.os == 'ubuntu-24.04' }}
      run: |
        sudo add-apt-repository -y 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${{ matrix.llvm }} main'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bison \
          build-essential \
          clang-${{ matrix.llvm }} \
          cmake \
          flex

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/
        mkdir build
        cd build
        bison -v ../src/ompparser.yy && ! cat ompparser.output | grep conflict
        cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON ..
        make tester

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        ! ../test_folder.sh ../tests | grep FAILED | grep [1-9]
