!$OMP  PARALLEL NUM_THREADS(3)
!$OMP        FLUSH
!$OMP        ATOMIC UPDATE
!$OMP           ATOMIC READ
!$OMP        FLUSH
!$OMP        FLUSH(DATA1)
!$OMP        ATOMIC UPDATE
!$OMP           ATOMIC READ
!$OMP        FLUSH(DATA0, DATA1)
!$OMP  END PARALLEL
